name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI/CD

    steps:
    - name: Execute remote deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          sudo chmod +x /root/soda-admin/CD.sh
          sudo chmod +x /root/soda-admin/deploy.sh
          ls -l /root/soda-admin/
          pwd
          echo "Executing CD.sh"
          sudo /root/soda-admin/CD.sh
